Fix AttributeError: '<the_type>' object has no attribute '__module__' in qt_isinstance
If an object is constructed with the wrong arguments, then the_type.__module__ may not exist.
Hence test for the __module__ attribute before testing its value